<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-UOSNP22B" failures="1" tests="1" name="Test" time="40.388" errors="0" timestamp="2024-06-13T07:37:48 IST">
  <testcase classname="AmazonTestCases.AmazonTest" name="tc01" time="10.692">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [24] but found [0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [24] but found [0]
at AmazonTestCases.AmazonTest.tc01(AmazonTest.java:160)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc01 -->
  <testcase classname="AmazonTestCases.AmazonTest" name="tc04" time="0.0">
    <ignored/>
  </testcase> <!-- tc04 -->
  <testcase classname="AmazonTestCases.AmazonTest" name="tc03" time="0.0">
    <ignored/>
  </testcase> <!-- tc03 -->
  <testcase classname="AmazonTestCases.AmazonTest" name="tc02" time="0.0">
    <ignored/>
  </testcase> <!-- tc02 -->
</testsuite> <!-- Test -->
